//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Ensure imports are used
var (
	_ runtime.Object
	_ metav1.Condition
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *BurnRateThreshold) DeepCopyInto(out *BurnRateThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *BurnRateThreshold) DeepCopy() *BurnRateThreshold {
	if in == nil { return nil }
	out := new(BurnRateThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SLOAlerting) DeepCopyInto(out *SLOAlerting) {
	*out = *in
	if in.BurnRateThresholds != nil {
		in, out := &in.BurnRateThresholds, &out.BurnRateThresholds
		*out = make([]BurnRateThreshold, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SLOAlerting) DeepCopy() *SLOAlerting {
	if in == nil { return nil }
	out := new(SLOAlerting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *SLOIndicator) DeepCopyInto(out *SLOIndicator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *SLOIndicator) DeepCopy() *SLOIndicator {
	if in == nil { return nil }
	out := new(SLOIndicator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveSpec) DeepCopyInto(out *ServiceLevelObjectiveSpec) {
	*out = *in
	out.Indicator = in.Indicator
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(SLOAlerting)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveSpec) DeepCopy() *ServiceLevelObjectiveSpec {
	if in == nil { return nil }
	out := new(ServiceLevelObjectiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveStatus) DeepCopyInto(out *ServiceLevelObjectiveStatus) {
	*out = *in
	if in.LastCalculation != nil {
		in, out := &in.LastCalculation, &out.LastCalculation
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveStatus) DeepCopy() *ServiceLevelObjectiveStatus {
	if in == nil { return nil }
	out := new(ServiceLevelObjectiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ServiceLevelObjective) DeepCopyInto(out *ServiceLevelObjective) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServiceLevelObjective) DeepCopy() *ServiceLevelObjective {
	if in == nil { return nil }
	out := new(ServiceLevelObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ServiceLevelObjective) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveList) DeepCopyInto(out *ServiceLevelObjectiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceLevelObjective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveList) DeepCopy() *ServiceLevelObjectiveList {
	if in == nil { return nil }
	out := new(ServiceLevelObjectiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ServiceLevelObjectiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// --- PodGuardPolicy ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodGuardRules) DeepCopyInto(out *PodGuardRules) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodGuardRules) DeepCopy() *PodGuardRules {
	if in == nil { return nil }
	out := new(PodGuardRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodGuardPolicySpec) DeepCopyInto(out *PodGuardPolicySpec) {
	*out = *in
	out.Rules = in.Rules
	if in.ExemptImages != nil {
		in, out := &in.ExemptImages, &out.ExemptImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExemptServiceAccounts != nil {
		in, out := &in.ExemptServiceAccounts, &out.ExemptServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodGuardPolicySpec) DeepCopy() *PodGuardPolicySpec {
	if in == nil { return nil }
	out := new(PodGuardPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodGuardPolicyStatus) DeepCopyInto(out *PodGuardPolicyStatus) {
	*out = *in
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodGuardPolicyStatus) DeepCopy() *PodGuardPolicyStatus {
	if in == nil { return nil }
	out := new(PodGuardPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodGuardPolicy) DeepCopyInto(out *PodGuardPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodGuardPolicy) DeepCopy() *PodGuardPolicy {
	if in == nil { return nil }
	out := new(PodGuardPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *PodGuardPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *PodGuardPolicyList) DeepCopyInto(out *PodGuardPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodGuardPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *PodGuardPolicyList) DeepCopy() *PodGuardPolicyList {
	if in == nil { return nil }
	out := new(PodGuardPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *PodGuardPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// --- ManagedNamespace ---

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ResourceQuotaSpec) DeepCopyInto(out *ResourceQuotaSpec) {
	*out = *in
	if in.Hard != nil {
		in, out := &in.Hard, &out.Hard
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ResourceQuotaSpec) DeepCopy() *ResourceQuotaSpec {
	if in == nil { return nil }
	out := new(ResourceQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *LimitRangeDefaults) DeepCopyInto(out *LimitRangeDefaults) {
	*out = *in
	if in.DefaultLimit != nil {
		in, out := &in.DefaultLimit, &out.DefaultLimit
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
	if in.DefaultRequest != nil {
		in, out := &in.DefaultRequest, &out.DefaultRequest
		*out = make(map[string]string, len(*in))
		for key, val := range *in { (*out)[key] = val }
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *LimitRangeDefaults) DeepCopy() *LimitRangeDefaults {
	if in == nil { return nil }
	out := new(LimitRangeDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil { return nil }
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *RBACSubject) DeepCopyInto(out *RBACSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *RBACSubject) DeepCopy() *RBACSubject {
	if in == nil { return nil }
	out := new(RBACSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *RBACBinding) DeepCopyInto(out *RBACBinding) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]RBACSubject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *RBACBinding) DeepCopy() *RBACBinding {
	if in == nil { return nil }
	out := new(RBACBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil { return nil }
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ManagedNamespaceSpec) DeepCopyInto(out *ManagedNamespaceSpec) {
	*out = *in
	if in.ResourceQuota != nil {
		in, out := &in.ResourceQuota, &out.ResourceQuota
		*out = new(ResourceQuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LimitRange != nil {
		in, out := &in.LimitRange, &out.LimitRange
		*out = new(LimitRangeDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = make([]RBACBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ManagedNamespaceSpec) DeepCopy() *ManagedNamespaceSpec {
	if in == nil { return nil }
	out := new(ManagedNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ManagedNamespaceStatus) DeepCopyInto(out *ManagedNamespaceStatus) {
	*out = *in
	if in.ResourcesCreated != nil {
		in, out := &in.ResourcesCreated, &out.ResourcesCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ManagedNamespaceStatus) DeepCopy() *ManagedNamespaceStatus {
	if in == nil { return nil }
	out := new(ManagedNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ManagedNamespace) DeepCopyInto(out *ManagedNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ManagedNamespace) DeepCopy() *ManagedNamespace {
	if in == nil { return nil }
	out := new(ManagedNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ManagedNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ManagedNamespaceList) DeepCopyInto(out *ManagedNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ManagedNamespaceList) DeepCopy() *ManagedNamespaceList {
	if in == nil { return nil }
	out := new(ManagedNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function.
func (in *ManagedNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
